dist:
  name: otelcol-dev
  description: Basic OTel Collector distribution for Developers
  output_path: ./otelcol-dev
  otelcol_version: 0.92.0
  debug_compilation: true

exporters:
  - gomod:
      # NOTE: Prior to v0.86.0 use the `loggingexporter` instead of `debugexporter`.
      go.opentelemetry.io/collector/exporter/debugexporter v0.92.0
  - gomod:
      go.opentelemetry.io/collector/exporter/otlpexporter v0.92.0
  - gomod:
      github.com/open-telemetry/opentelemetry-collector-contrib/exporter/fileexporter v0.92.0
#    import: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/fileexporter
##    import: "/Users/sswartz/workspace/opentelemetry-collector-contrib/exporter/fileexporter"
#    path: "/Users/sswartz/workspace/opentelemetry-collector-contrib/exporter/fileexporter"
    path: "/Users/sswartz/workspace/opentelemetry-collector-contrib/exporter/fileexporter"
#    name: fileexporter
#  - gomod:
#      github.com/open-telemetry/opentelemetry-collector-contrib/exporter/rabbitmqexporter v0.92.0
#    path: "/Users/sswartz/workspace/opentelemetry-collector-contrib/exporter/rabbitmqexporter"

processors:
  - gomod:
      go.opentelemetry.io/collector/processor/batchprocessor v0.92.0

receivers:
  - gomod:
      go.opentelemetry.io/collector/receiver/otlpreceiver v0.92.0
  - gomod:
      github.com/open-telemetry/opentelemetry-collector-contrib/receiver/statsdreceiver v0.92.0

extensions:
  - gomod:
      github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckextension v0.92.0
    path: "/Users/sswartz/workspace/opentelemetry-collector-contrib/extension/healthcheckextension"